name: Build and Publish Electron App

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-2025

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Compile and Publish Desktop Executable
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Changed to the built-in safe token
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true